### ISSUE TITLE
erdpy lacks API documentation

### ISSUE THREAD

**Issue by miohtama** [multiversx/mx-sdk-py-cli#39]
erdpy does not have manually maintained or automatically generated API documentation.

This makes the library very difficult to use, as one needs to read a lot of source code to achieve some of the basic functionality. This greatly increase the development time with this library for anybody, but the original author, bringing down the library value and making it harder for Python developers to enter Elrond ecosystem.

A good example of Python partly generated, party written narrative API documentation is [web3.py](https://web3py.readthedocs.io/en/stable/web3.main.html).

**Comment by popenta** [comment]
`mxpy` should not be used as a package anymore because now we have dedicated python sdk's. Check out the sdk's [here](https://docs.multiversx.com/sdk-and-tools/sdk-py/#sdk-py-the-python-libraries).

You can check out the mxpy documentation [here](https://github.com/multiversx/mx-sdk-py-cli/blob/main/CLI.md)  or you could simply use `mxpy <command> --help` when using the cli.

For the sdk's we have a cookbook, you can take a look [here](https://docs.multiversx.com/sdk-and-tools/sdk-py/sdk-py-cookbook).
